### ISSUE TITLE
setQuery method is not available. Attached screenshot details for the same

### ISSUE THREAD

**Issue by premkh9** [basdijkstra/restassured-graphql#1]
![image](https://user-images.githubusercontent.com/14880073/137043640-7a4b0004-09e9-4584-a507-c56d11553f75.png)

**Comment by basdijkstra** [comment]
Hey @premkh9. yes, it is available. IntelliJ just doesn't recognize it, because it's added at compile time by [Lombok](https://projectlombok.org/). If you add the [Lombok plugin](https://plugins.jetbrains.com/plugin/6317-lombok) to your IntelliJ installation all should be fine.

If you run the tests, you'll see they run and pass even though IntelliJ states the `setQuery` method is not available.
